INSERT INTO TB_CATEGORY(NAME)VALUES('Java');
INSERT INTO TB_CATEGORY(NAME)VALUES('Kotlin');
INSERT INTO TB_CATEGORY(NAME)VALUES('PHP');
INSERT INTO TB_CATEGORY(NAME)VALUES('Node JS');
INSERT INTO TB_CATEGORY(NAME)VALUES('React');
INSERT INTO TB_CATEGORY(NAME)VALUES('Python');
INSERT INTO TB_CATEGORY(NAME)VALUES('React Native');

INSERT INTO TB_CATEGORY(NAME)VALUES('Java Script');
INSERT INTO TB_CATEGORY(NAME)VALUES('WordPress');
INSERT INTO TB_CATEGORY(NAME)VALUES('GO');
INSERT INTO TB_CATEGORY(NAME)VALUES('Ciência de Dados');
INSERT INTO TB_CATEGORY(NAME)VALUES('Engenharia de Dados');